# Generated by Django 5.2 on 2025-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80)),
                ('Body', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('Created', models.DateField(auto_now_add=True)),
                ('Updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
