# Generated by Django 5.2 on 2025-04-22 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 22, 12, 13, 12, 411853, tzinfo=datetime.timezone.utc)),
        ),
    ]
