# Generated by Django 5.2 on 2025-04-23 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_article_pb_timezone_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 11, 46, 46, 594487, tzinfo=datetime.timezone.utc)),
        ),
    ]
