# Generated by Django 5.2 on 2025-04-23 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_pb_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 12, 2, 59, 991148, tzinfo=datetime.timezone.utc)),
        ),
    ]
