# Generated by Django 5.2 on 2025-04-26 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_pb_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 26, 14, 55, 21, 586692, tzinfo=datetime.timezone.utc)),
        ),
    ]
