# Generated by Django 5.2 on 2025-04-30 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_options_alter_article_pb_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 15, 32, 0, 194499, tzinfo=datetime.timezone.utc)),
        ),
    ]
