# Generated by Django 5.2 on 2025-04-30 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_pb_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Pb_Timezone',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 15, 33, 5, 882510, tzinfo=datetime.timezone.utc)),
        ),
    ]
